env:
  RUNNER_DEBUG: 1

name: "Github Action Test"
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - '.github/workflows/action-test.yml'
      - 'setup-action/**'
  push:
    branches:
      - $default-branch
    paths:
      - '.github/workflows/action-test.yml'
      - 'setup-action/**'

jobs:
  build: # make sure build/ci work properly
    defaults:
      run:
        working-directory: setup-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run build
    - name: check for changes
      run: git diff --exit-code
  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - run: find.

    - uses: ./setups-action/
      id: install

    - name: Get the helm-charts-semantic-releaser
      run: helm-charts-semantic-releaser --help
